name: Build Docker Image

on:
  workflow_dispatch:
    inputs:
      desc:
        description: "desc"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: bytebin
          push: true
          tags: kagurazakanyaa/luckperms:bytebin

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: web
          push: true
          tags: kagurazakanyaa/luckperms:web
